--  crear usuarios 
create user  C##ALUMNOS IDENTIFIED BY "123";
create user  C##MATRICULAS IDENTIFIED BY "123";

--PERMISO DE SESION

GRANT CREATE SESSION TO c##ALUMNOS;
GRANT CREATE SESSION TO c##MATRICULAS;

--PERMISO PARA LAS TABLAS 
GRANT CREATE TABLE TO c##ALUMNOS;
GRANT CREATE TABLE TO c##MATRICULAS;


--ESPCIO ILIMITADOS ALOS TABLASSPACE USER
ALTER USER  c##ALUMNOS QUOTA UNLIMITED ON USERS;
ALTER USER  c##MATRICULAS QUOTA UNLIMITED ON USERS;

--ASIGANMAOS PERMISO ENTRE ESQUEMAS
GRANT SELECT ON c##ALUMNOS.ALUMNOS TO c##MATRICULAS;



--ESQUEMAS  DE ALUMOS
CREATE TABLE ALUMNOS(
ID_ALUMNO NUMBER PRIMARY KEY,
NOMBRE VARCHAR2(50),
APELLIDO_PATERNO VARCHAR2(100),
APELLIDO_MATERNO VARCHAR2 (100),
TELEFONO VARCHAR2 (50)
)

-- Insertar registros
INSERT INTO ALUMNOS VALUES (1, 'STIVEN', 'SKILL', 'CHUMKI', '987654321');
INSERT INTO ALUMNOS VALUES (2, 'YULER', 'CCENTE', 'QUISPE', '912345678');

COMMIT;


SELECT * FROM alumnos;

--ESQUEMAS DE MATRICULAS



CREATE TABLE CARRERA(
ID_CARRERA NUMBER PRIMARY KEY,
NOMBRE_CARRERA VARCHAR2 (50)
);

CREATE TABLE MATRICULAS(
ID_MATRICULA NUMBER PRIMARY KEY,
ID_ALUMNO NUMBER,
ID_CARRERA NUMBER,
CICLO VARCHAR2(50),
MONTO NUMBER (8,2)
);

INSERT INTO CARRERA VALUES (1, 'INGENIERÍA DE SISTEMAS');
INSERT INTO CARRERAS
VALUES (2, 'ADMINISTRACIÓN');
INSERT INTO CARRERA VALUES (3, 'CONTABILIDAD');
COMMIT;
SELECT  * FROM CARRERA;
SELECT  * FROM MATRICULAS;

INSERT INTO MATRICULAS VALUES (1, 1, 1, '2025-I', 850.00);
INSERT INTO MATRICULAS VALUES (2, 1, 2, '2025-I', 780.00);
INSERT INTO MATRICULAS VALUES (3, 2, 3, '2025-I', 720.00);
COMMIT;


SELECT * FROM C##ALUMNOS.ALUMNOS;

--conusltas de datos de los alumons
SELECT 
    c.NOMBRE_CARRERA AS CARRERA,
    m.CICLO,
    m.MONTO AS MONTO_MATRICULA
FROM MATRICULAS m
JOIN CARRERA c
    ON m.ID_CARRERA = c.ID_CARRERA;
    
    
    DECLARE
    base NUMBER := 10;
    altura NUMBER := 5;
    area NUMBER;
BEGIN
    area := (base * altura) / 2;
    DBMS_OUTPUT.PUT_LINE('Área del triángulo: ' || area);
END;
commit;
/


